"""Script to create the problem statement notebook."""
import json

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 📈 Financial Market Trend Forecasting\n",
                "## Problem Statement & Project Documentation\n",
                "\n",
                "---\n",
                "\n",
                "**Project:** Financial Market Trend Forecasting for Indian Equities  \n",
                "**Data Window:** January 1, 2023 – January 1, 2026  \n",
                "**Author:** Financial Analytics Research Team  \n",
                "**Version:** 1.0\n",
                "\n",
                "---"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Table of Contents\n",
                "\n",
                "1. [Problem Statement](#1-problem-statement)\n",
                "2. [Project Objective](#2-project-objective)\n",
                "3. [Research Question](#3-research-question)\n",
                "4. [Data Sources](#4-data-sources)\n",
                "5. [Machine Learning Problem Formulation](#5-machine-learning-problem-formulation)\n",
                "6. [Volatility-Based Stock Classification](#6-volatility-based-stock-classification)\n",
                "7. [Models Used](#7-models-used)\n",
                "8. [Evaluation Metrics](#8-evaluation-metrics)\n",
                "9. [System Architecture](#9-system-architecture)\n",
                "10. [Expected Outcome](#10-expected-outcome)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "\n",
                "## 1. Problem Statement\n",
                "\n",
                "### 1.1 The Stock Market Prediction Challenge\n",
                "\n",
                "Stock market prediction is one of the most challenging problems in financial analytics. Investors, traders, and financial institutions constantly seek methods to anticipate market movements to make informed decisions. The ability to predict stock price movements can lead to:\n",
                "\n",
                "- **Better investment decisions**\n",
                "- **Improved portfolio management**\n",
                "- **Risk mitigation strategies**\n",
                "- **Automated trading systems**\n",
                "\n",
                "### 1.2 Why Predicting Exact Price is Difficult\n",
                "\n",
                "Predicting the exact future stock price is extremely challenging due to several factors:\n",
                "\n",
                "| Factor | Description |\n",
                "|--------|-------------|\n",
                "| **Market Volatility** | Stock prices fluctuate rapidly due to supply-demand dynamics |\n",
                "| **Random Walk Theory** | Price movements often follow unpredictable patterns |\n",
                "| **External Events** | Geopolitical events, news, and sentiment cause sudden shifts |\n",
                "| **Information Asymmetry** | Not all market participants have equal access to information |\n",
                "| **Non-Linear Relationships** | Complex interactions between multiple variables |\n",
                "| **High Dimensionality** | Numerous factors influence price simultaneously |\n",
                "\n",
                "The Efficient Market Hypothesis (EMH) suggests that stock prices already reflect all available information, making consistent prediction nearly impossible. Additionally, financial markets exhibit:\n",
                "\n",
                "- **Non-stationarity**: Statistical properties change over time\n",
                "- **Heteroscedasticity**: Variance of returns changes with time\n",
                "- **Fat tails**: Extreme events occur more frequently than normal distribution suggests\n",
                "\n",
                "### 1.3 Why Trend Classification Over Regression\n",
                "\n",
                "Given the difficulty in predicting exact prices, this project adopts a **trend classification approach** instead of regression:\n",
                "\n",
                "| Approach | Target | Complexity | Practical Use |\n",
                "|----------|--------|------------|---------------|\n",
                "| **Regression** | Exact price value | Very High | Limited actionability |\n",
                "| **Classification** | Up or Down trend | Moderate | Directly actionable |\n",
                "\n",
                "**Advantages of Trend Classification:**\n",
                "\n",
                "1. **Actionable Signals**: Binary signals (Buy/Sell) are directly usable for trading\n",
                "2. **Noise Reduction**: Small price fluctuations are filtered out\n",
                "3. **Clearer Evaluation**: Accuracy, precision, and recall provide interpretable metrics\n",
                "4. **Robustness**: Less sensitive to outliers compared to regression\n",
                "5. **Risk Management**: Easier to set stop-loss and take-profit levels"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "\n",
                "## 2. Project Objective\n",
                "\n",
                "### 2.1 Primary Goals\n",
                "\n",
                "This project aims to achieve the following objectives:\n",
                "\n",
                "#### 🎯 Goal 1: Build a Trend Prediction System for Indian Stock Market\n",
                "\n",
                "Develop a comprehensive machine learning system capable of predicting next-day price movement direction for stocks in the Nifty 500 index.\n",
                "\n",
                "**Key deliverables:**\n",
                "- Multi-source data pipeline\n",
                "- Feature engineering framework\n",
                "- Trained prediction models\n",
                "- Prediction API\n",
                "- Web dashboard\n",
                "\n",
                "#### 🎯 Goal 2: Compare Ensemble Learning vs Deep Learning Models\n",
                "\n",
                "Conduct a systematic comparison between:\n",
                "\n",
                "| Model Type | Models | Characteristics |\n",
                "|------------|--------|------------------|\n",
                "| **Ensemble Learning** | Random Forest, XGBoost | Tree-based, interpretable |\n",
                "| **Deep Learning** | LSTM, Transformer | Sequence modeling, complex patterns |\n",
                "\n",
                "#### 🎯 Goal 3: Study Model Performance Under Different Volatility Regimes\n",
                "\n",
                "Investigate how model performance varies across stock volatility categories:\n",
                "\n",
                "```\n",
                "┌─────────────────────────────────────────────────────────┐\n",
                "│                   VOLATILITY REGIMES                    │\n",
                "├───────────────┬───────────────┬─────────────────────────┤\n",
                "│   VOLATILE    │    STABLE     │     NON-VOLATILE       │\n",
                "│   (Top 33%)   │  (Mid 33%)    │     (Bottom 33%)       │\n",
                "│               │               │                         │\n",
                "│ High risk     │ Moderate      │ Low risk               │\n",
                "│ High return   │ movement      │ Steady growth          │\n",
                "└───────────────┴───────────────┴─────────────────────────┘\n",
                "```"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "\n",
                "## 3. Research Question\n",
                "\n",
                "### Primary Research Question\n",
                "\n",
                "> **\"Which model performs best for stock trend prediction under different volatility regimes in the Indian stock market?\"**\n",
                "\n",
                "### Sub-Questions\n",
                "\n",
                "1. **Performance Comparison**: How do ensemble methods (Random Forest, XGBoost) compare against deep learning models (LSTM, Transformer) in predicting stock trends?\n",
                "\n",
                "2. **Volatility Impact**: Does stock volatility significantly affect model performance? Do certain models excel in specific volatility regimes?\n",
                "\n",
                "3. **Feature Importance**: Which features (technical indicators, sentiment, global markets, macro data) contribute most to prediction accuracy?\n",
                "\n",
                "4. **Generalization**: How well do models trained on historical data generalize to unseen market conditions?\n",
                "\n",
                "### Hypothesis\n",
                "\n",
                "| Hypothesis | Description |\n",
                "|------------|-------------|\n",
                "| H1 | Deep learning models will outperform ensemble methods for volatile stocks |\n",
                "| H2 | Ensemble methods will be more stable across all volatility regimes |\n",
                "| H3 | External features (sentiment, global markets) will improve prediction accuracy |\n",
                "| H4 | Model performance will vary significantly across volatility categories |"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "\n",
                "## 4. Data Sources\n",
                "\n",
                "The project leverages six distinct data sources to create a comprehensive feature set:\n",
                "\n",
                "### 4.1 Data Source Overview\n",
                "\n",
                "```\n",
                "┌──────────────────────────────────────────────────────────────────┐\n",
                "│                        DATA SOURCES                              │\n",
                "├──────────────────────────────────────────────────────────────────┤\n",
                "│                                                                  │\n",
                "│  ┌──────────────┐    ┌──────────────┐    ┌──────────────┐       │\n",
                "│  │   YAHOO      │    │   TA-LIB     │    │   YAHOO      │       │\n",
                "│  │   FINANCE    │    │  TECHNICAL   │    │   GLOBAL     │       │\n",
                "│  │   (OHLCV)    │    │  INDICATORS  │    │   INDICES    │       │\n",
                "│  └──────────────┘    └──────────────┘    └──────────────┘       │\n",
                "│                                                                  │\n",
                "│  ┌──────────────┐    ┌──────────────┐    ┌──────────────┐       │\n",
                "│  │    ALPHA     │    │    GDELT     │    │     FRED     │       │\n",
                "│  │   VANTAGE    │    │    GLOBAL    │    │    MACRO     │       │\n",
                "│  │  (SENTIMENT) │    │   EVENTS     │    │    DATA      │       │\n",
                "│  └──────────────┘    └──────────────┘    └──────────────┘       │\n",
                "│                                                                  │\n",
                "└──────────────────────────────────────────────────────────────────┘\n",
                "```\n",
                "\n",
                "### 4.2 Detailed Source Information\n",
                "\n",
                "#### 📊 Source 1: Yahoo Finance — Stock Price Data\n",
                "| Attribute | Details |\n",
                "|-----------|----------|\n",
                "| **Data Type** | OHLCV (Open, High, Low, Close, Volume) |\n",
                "| **Coverage** | Nifty 500 stocks + Nifty index |\n",
                "| **Frequency** | Daily |\n",
                "| **Period** | 2023-01-01 to 2026-01-01 |\n",
                "\n",
                "#### 📈 Source 2: TA-Lib — Technical Indicators\n",
                "| Indicator Category | Examples |\n",
                "|-------------------|----------|\n",
                "| **Momentum** | RSI, MACD |\n",
                "| **Trend** | EMA, SMA |\n",
                "| **Volatility** | Bollinger Bands |\n",
                "| **Volume** | OBV, Volume SMA |\n",
                "\n",
                "#### 🌍 Source 3: Yahoo Finance — Global Market Indices\n",
                "| Symbol | Description |\n",
                "|--------|-------------|\n",
                "| `^GSPC` | S&P 500 |\n",
                "| `^IXIC` | NASDAQ Composite |\n",
                "| `^DJI` | Dow Jones Industrial Average |\n",
                "| `GC=F` | Gold Futures |\n",
                "| `CL=F` | Crude Oil Futures |\n",
                "| `INR=X` | USD/INR Exchange Rate |\n",
                "| `^VIX` | CBOE Volatility Index |\n",
                "\n",
                "#### 📰 Source 4: Alpha Vantage — News Sentiment\n",
                "| Feature | Description |\n",
                "|---------|-------------|\n",
                "| **Sentiment Score** | Daily sentiment aggregate (-1 to +1) |\n",
                "| **Article Count** | Number of news articles per day |\n",
                "| **Ticker Coverage** | Stock-specific sentiment |\n",
                "\n",
                "#### 🌐 Source 5: GDELT — Global Events\n",
                "| Feature | Description |\n",
                "|---------|-------------|\n",
                "| **Event Count** | Daily count of global events |\n",
                "| **Tone** | Average tone of event coverage |\n",
                "| **Themes** | Event categories (War, Crisis, Inflation, etc.) |\n",
                "\n",
                "#### 🏛️ Source 6: FRED — Macroeconomic Data\n",
                "| Indicator | Description |\n",
                "|-----------|-------------|\n",
                "| **Interest Rate** | Federal funds rate |\n",
                "| **Inflation** | Consumer Price Index |\n",
                "| **Unemployment** | Unemployment rate |\n",
                "| **GDP** | Gross Domestic Product |"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "\n",
                "## 5. Machine Learning Problem Formulation\n",
                "\n",
                "### 5.1 Problem Type\n",
                "\n",
                "This project is formulated as a **Binary Classification Problem**.\n",
                "\n",
                "### 5.2 Target Variable Definition\n",
                "\n",
                "The target variable represents the next-day price movement direction:\n",
                "\n",
                "**Target Rule:**\n",
                "- **Target = 1** if Close(t+1) > Close(t) → Uptrend\n",
                "- **Target = 0** if Close(t+1) ≤ Close(t) → Downtrend"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Target Variable Formula (Illustrative)\n",
                "def calculate_target(close_today, close_tomorrow):\n",
                "    \"\"\"\n",
                "    Calculate binary target for trend prediction.\n",
                "    \n",
                "    Args:\n",
                "        close_today: Today's closing price\n",
                "        close_tomorrow: Tomorrow's closing price\n",
                "    \n",
                "    Returns:\n",
                "        1 if uptrend, 0 if downtrend\n",
                "    \"\"\"\n",
                "    if close_tomorrow > close_today:\n",
                "        return 1  # Uptrend\n",
                "    else:\n",
                "        return 0  # Downtrend"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### 5.3 Classification Framework\n",
                "\n",
                "```\n",
                "┌────────────────────────────────────────────────────────┐\n",
                "│              BINARY CLASSIFICATION SETUP               │\n",
                "├────────────────────────────────────────────────────────┤\n",
                "│                                                        │\n",
                "│   INPUT FEATURES                    TARGET             │\n",
                "│   ┌────────────────┐               ┌─────────┐        │\n",
                "│   │ Price Data     │               │         │        │\n",
                "│   │ Technical Ind. │    ────►      │  0 or 1 │        │\n",
                "│   │ Global Markets │    MODEL      │         │        │\n",
                "│   │ News Sentiment │    ────►      │  Down   │        │\n",
                "│   │ GDELT Events   │               │   or    │        │\n",
                "│   │ Macro Data     │               │   Up    │        │\n",
                "│   └────────────────┘               └─────────┘        │\n",
                "│                                                        │\n",
                "└────────────────────────────────────────────────────────┘\n",
                "```\n",
                "\n",
                "### 5.4 Important Considerations\n",
                "\n",
                "| Aspect | Implementation |\n",
                "|--------|----------------|\n",
                "| **Data Leakage Prevention** | Target is shifted by 1 day to avoid look-ahead bias |\n",
                "| **Time Series Split** | No random splitting; chronological train/validation/test |\n",
                "| **Feature Lagging** | Global and news data lagged by 1 day |\n",
                "| **Class Balance** | Monitor for class imbalance in target variable |"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "\n",
                "## 6. Volatility-Based Stock Classification\n",
                "\n",
                "### 6.1 Volatility Calculation\n",
                "\n",
                "Stock volatility is measured using the **standard deviation of daily returns**.\n",
                "\n",
                "**Mathematical Formula:**\n",
                "\n",
                "```\n",
                "Daily Return = (Close_t - Close_t-1) / Close_t-1\n",
                "\n",
                "Volatility = Standard Deviation of Daily Returns\n",
                "```"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Volatility Calculation (Illustrative)\n",
                "import numpy as np\n",
                "\n",
                "def calculate_volatility(prices):\n",
                "    \"\"\"\n",
                "    Calculate stock volatility as standard deviation of daily returns.\n",
                "    \n",
                "    Args:\n",
                "        prices: Array of closing prices\n",
                "    \n",
                "    Returns:\n",
                "        Volatility (standard deviation of returns)\n",
                "    \"\"\"\n",
                "    returns = np.diff(prices) / prices[:-1]\n",
                "    volatility = np.std(returns)\n",
                "    return volatility"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### 6.2 Volatility Categories\n",
                "\n",
                "Stocks are classified into three categories based on their volatility percentile:\n",
                "\n",
                "```\n",
                "┌────────────────────────────────────────────────────────────────┐\n",
                "│                    VOLATILITY DISTRIBUTION                      │\n",
                "├────────────────────────────────────────────────────────────────┤\n",
                "│                                                                 │\n",
                "│     ▲                                                          │\n",
                "│     │                         ┌──────────┐                     │\n",
                "│     │                         │ VOLATILE │                     │\n",
                "│  F  │            ┌────────────┤ Top 33%  │                     │\n",
                "│  r  │            │  STABLE    └──────────┘                     │\n",
                "│  e  │  ┌─────────┤ Middle 33% │                                │\n",
                "│  q  │  │NON-VOL. └────────────┘                                │\n",
                "│  u  │  │Bottom   │                                             │\n",
                "│  e  │  │  33%    │                                             │\n",
                "│  n  │  └─────────┘                                             │\n",
                "│  c  │                                                          │\n",
                "│  y  └──────────────────────────────────────────────────►       │\n",
                "│                         Volatility (σ)                         │\n",
                "│                                                                 │\n",
                "└────────────────────────────────────────────────────────────────┘\n",
                "```\n",
                "\n",
                "### 6.3 Category Definitions\n",
                "\n",
                "| Category | Percentile Range | Characteristics | Example Sectors |\n",
                "|----------|-----------------|-----------------|------------------|\n",
                "| **Volatile** | Top 33% (67th - 100th) | High price swings, higher risk/reward | Small-cap, Tech, Pharma |\n",
                "| **Stable** | Middle 33% (33rd - 67th) | Moderate movements | Mid-cap, Banking |\n",
                "| **Non-Volatile** | Bottom 33% (0 - 33rd) | Low price swings, steady growth | Large-cap, FMCG, Utilities |"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Volatility Classification Logic (Illustrative)\n",
                "import numpy as np\n",
                "\n",
                "def classify_volatility(volatility_values):\n",
                "    \"\"\"\n",
                "    Classify stocks into volatility categories.\n",
                "    \n",
                "    Args:\n",
                "        volatility_values: Array of volatility values for all stocks\n",
                "    \n",
                "    Returns:\n",
                "        List of category labels\n",
                "    \"\"\"\n",
                "    p33 = np.percentile(volatility_values, 33)\n",
                "    p67 = np.percentile(volatility_values, 67)\n",
                "    \n",
                "    categories = []\n",
                "    for v in volatility_values:\n",
                "        if v <= p33:\n",
                "            categories.append('Non-Volatile')\n",
                "        elif v <= p67:\n",
                "            categories.append('Stable')\n",
                "        else:\n",
                "            categories.append('Volatile')\n",
                "    \n",
                "    return categories"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "\n",
                "## 7. Models Used\n",
                "\n",
                "The project employs four machine learning models, representing both ensemble learning and deep learning approaches:\n",
                "\n",
                "### 7.1 Model Overview\n",
                "\n",
                "```\n",
                "┌────────────────────────────────────────────────────────────────┐\n",
                "│                      MODEL ARCHITECTURE                        │\n",
                "├────────────────────────────────────────────────────────────────┤\n",
                "│                                                                 │\n",
                "│   ENSEMBLE LEARNING              DEEP LEARNING                 │\n",
                "│   ┌─────────────────┐           ┌─────────────────┐            │\n",
                "│   │                 │           │                 │            │\n",
                "│   │  Random Forest  │           │      LSTM       │            │\n",
                "│   │   (Bagging)     │           │  (Sequential)   │            │\n",
                "│   │                 │           │                 │            │\n",
                "│   └─────────────────┘           └─────────────────┘            │\n",
                "│                                                                 │\n",
                "│   ┌─────────────────┐           ┌─────────────────┐            │\n",
                "│   │                 │           │                 │            │\n",
                "│   │    XGBoost      │           │  Transformer    │            │\n",
                "│   │   (Boosting)    │           │  (Attention)    │            │\n",
                "│   │                 │           │                 │            │\n",
                "│   └─────────────────┘           └─────────────────┘            │\n",
                "│                                                                 │\n",
                "└────────────────────────────────────────────────────────────────┘\n",
                "```\n",
                "\n",
                "### 7.2 Model Details\n",
                "\n",
                "#### 🌲 Random Forest\n",
                "\n",
                "| Aspect | Description |\n",
                "|--------|-------------|\n",
                "| **Type** | Ensemble (Bagging) |\n",
                "| **Base Learner** | Decision Trees |\n",
                "| **Key Strength** | Handles non-linear relationships, feature importance |\n",
                "| **Interpretability** | High |\n",
                "| **Training Speed** | Fast |\n",
                "\n",
                "#### 🚀 XGBoost\n",
                "\n",
                "| Aspect | Description |\n",
                "|--------|-------------|\n",
                "| **Type** | Ensemble (Gradient Boosting) |\n",
                "| **Base Learner** | Decision Trees |\n",
                "| **Key Strength** | High accuracy, handles missing values |\n",
                "| **Regularization** | L1 and L2 |\n",
                "| **Training Speed** | Fast with GPU support |\n",
                "\n",
                "#### 🔄 LSTM (Long Short-Term Memory)\n",
                "\n",
                "| Aspect | Description |\n",
                "|--------|-------------|\n",
                "| **Type** | Deep Learning (RNN variant) |\n",
                "| **Architecture** | Recurrent with memory cells |\n",
                "| **Key Strength** | Captures temporal dependencies |\n",
                "| **Best For** | Sequential patterns in time series |\n",
                "| **Training Speed** | Moderate |\n",
                "\n",
                "#### ⚡ Transformer\n",
                "\n",
                "| Aspect | Description |\n",
                "|--------|-------------|\n",
                "| **Type** | Deep Learning (Attention-based) |\n",
                "| **Architecture** | Self-attention mechanism |\n",
                "| **Key Strength** | Parallel processing, long-range dependencies |\n",
                "| **Best For** | Complex pattern recognition |\n",
                "| **Training Speed** | Fast with GPU |"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "\n",
                "## 8. Evaluation Metrics\n",
                "\n",
                "### 8.1 Metrics Overview\n",
                "\n",
                "Model performance is evaluated using multiple classification metrics:\n",
                "\n",
                "```\n",
                "┌────────────────────────────────────────────────────────────────┐\n",
                "│                    EVALUATION METRICS                          │\n",
                "├────────────────────────────────────────────────────────────────┤\n",
                "│                                                                 │\n",
                "│   ┌──────────┐  ┌───────────┐  ┌────────┐  ┌──────────┐       │\n",
                "│   │ ACCURACY │  │ PRECISION │  │ RECALL │  │ F1 SCORE │       │\n",
                "│   └──────────┘  └───────────┘  └────────┘  └──────────┘       │\n",
                "│                                                                 │\n",
                "│                  ┌───────────────────┐                         │\n",
                "│                  │ CONFUSION MATRIX  │                         │\n",
                "│                  └───────────────────┘                         │\n",
                "│                                                                 │\n",
                "└────────────────────────────────────────────────────────────────┘\n",
                "```\n",
                "\n",
                "### 8.2 Metric Definitions\n",
                "\n",
                "#### Accuracy\n",
                "```\n",
                "Accuracy = (TP + TN) / (TP + TN + FP + FN)\n",
                "```\n",
                "**Interpretation:** Overall correctness of predictions.\n",
                "\n",
                "#### Precision\n",
                "```\n",
                "Precision = TP / (TP + FP)\n",
                "```\n",
                "**Interpretation:** Of all predicted uptrends, how many were actually uptrends?\n",
                "\n",
                "#### Recall (Sensitivity)\n",
                "```\n",
                "Recall = TP / (TP + FN)\n",
                "```\n",
                "**Interpretation:** Of all actual uptrends, how many did we correctly predict?\n",
                "\n",
                "#### F1 Score\n",
                "```\n",
                "F1 = 2 × (Precision × Recall) / (Precision + Recall)\n",
                "```\n",
                "**Interpretation:** Harmonic mean of precision and recall.\n",
                "\n",
                "### 8.3 Confusion Matrix\n",
                "\n",
                "```\n",
                "                      PREDICTED\n",
                "                 ┌─────────┬─────────┐\n",
                "                 │ Down(0) │  Up(1)  │\n",
                "        ┌────────┼─────────┼─────────┤\n",
                "        │Down(0) │   TN    │   FP    │\n",
                "ACTUAL  ├────────┼─────────┼─────────┤\n",
                "        │ Up(1)  │   FN    │   TP    │\n",
                "        └────────┴─────────┴─────────┘\n",
                "        \n",
                "Where:\n",
                "  TP = True Positive  (Correctly predicted Up)\n",
                "  TN = True Negative  (Correctly predicted Down)\n",
                "  FP = False Positive (Incorrectly predicted Up)\n",
                "  FN = False Negative (Incorrectly predicted Down)\n",
                "```\n",
                "\n",
                "### 8.4 Model Selection Strategy\n",
                "\n",
                "| Phase | Data Split | Purpose |\n",
                "|-------|-----------|----------|\n",
                "| Training | Train Set | Model learning |\n",
                "| Validation | Validation Set | Hyperparameter tuning & model selection |\n",
                "| Testing | Test Set | Final performance reporting |"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "\n",
                "## 9. System Architecture\n",
                "\n",
                "### 9.1 High-Level Pipeline\n",
                "\n",
                "```\n",
                "┌──────────────────────────────────────────────────────────────────────────────┐\n",
                "│                         SYSTEM ARCHITECTURE                                   │\n",
                "├──────────────────────────────────────────────────────────────────────────────┤\n",
                "│                                                                               │\n",
                "│  ┌─────────────┐    ┌─────────────┐    ┌─────────────┐    ┌─────────────┐   │\n",
                "│  │    DATA     │    │    DATA     │    │   FEATURE   │    │    MODEL    │   │\n",
                "│  │   SOURCES   │───►│ PROCESSING  │───►│ ENGINEERING │───►│  TRAINING   │   │\n",
                "│  │             │    │             │    │             │    │             │   │\n",
                "│  └─────────────┘    └─────────────┘    └─────────────┘    └─────────────┘   │\n",
                "│        │                                                         │           │\n",
                "│        │                                                         ▼           │\n",
                "│        │                                                  ┌─────────────┐   │\n",
                "│        │                                                  │    MODEL    │   │\n",
                "│        │                                                  │  SELECTION  │   │\n",
                "│        │                                                  │             │   │\n",
                "│        │                                                  └─────────────┘   │\n",
                "│        │                                                         │           │\n",
                "│        │                                                         ▼           │\n",
                "│        │            ┌─────────────┐    ┌─────────────┐    ┌─────────────┐   │\n",
                "│        │            │   WEB APP   │◄───│ PREDICTION  │◄───│   BEST      │   │\n",
                "│        └───────────►│  DASHBOARD  │    │     API     │    │   MODEL     │   │\n",
                "│                     │             │    │             │    │             │   │\n",
                "│                     └─────────────┘    └─────────────┘    └─────────────┘   │\n",
                "│                                                                               │\n",
                "└──────────────────────────────────────────────────────────────────────────────┘\n",
                "```\n",
                "\n",
                "### 9.2 Component Description\n",
                "\n",
                "| Component | Description | Technology |\n",
                "|-----------|-------------|------------|\n",
                "| **Data Sources** | Multi-source data collection | Yahoo Finance, Alpha Vantage, GDELT, FRED APIs |\n",
                "| **Data Processing** | Cleaning, validation, alignment | Pandas, NumPy |\n",
                "| **Feature Engineering** | Technical indicators, derived features | TA-Lib, custom modules |\n",
                "| **Model Training** | Train all models per volatility category | Scikit-learn, XGBoost, TensorFlow/PyTorch |\n",
                "| **Model Selection** | Compare and select best model | Custom evaluation framework |\n",
                "| **Prediction API** | Serve predictions via REST API | FastAPI/Flask |\n",
                "| **Web App** | User interface dashboard | React/Streamlit |\n",
                "\n",
                "### 9.3 Data Flow Pipeline\n",
                "\n",
                "```\n",
                "┌─────────────────────────────────────────────────────────────────────────┐\n",
                "│                          DATA FLOW PIPELINE                             │\n",
                "├─────────────────────────────────────────────────────────────────────────┤\n",
                "│                                                                         │\n",
                "│   RAW DATA           PROCESSED DATA        FEATURES          FINAL     │\n",
                "│                                                                         │\n",
                "│  ┌─────────┐        ┌─────────────┐      ┌──────────┐    ┌─────────┐  │\n",
                "│  │ Yahoo   │        │  Cleaned    │      │ Technical│    │ Model   │  │\n",
                "│  │ Finance │───────►│  OHLCV      │─────►│ Indicators───►│ Ready   │  │\n",
                "│  └─────────┘        └─────────────┘      └──────────┘    │ Dataset │  │\n",
                "│                                                           │         │  │\n",
                "│  ┌─────────┐        ┌─────────────┐      ┌──────────┐    │         │  │\n",
                "│  │ Global  │        │  Lagged     │      │ Return   │    │         │  │\n",
                "│  │ Markets │───────►│  Returns    │─────►│ Features │───►│         │  │\n",
                "│  └─────────┘        └─────────────┘      └──────────┘    │         │  │\n",
                "│                                                           │         │  │\n",
                "│  ┌─────────┐        ┌─────────────┐      ┌──────────┐    │         │  │\n",
                "│  │ News    │        │  Lagged     │      │ Sentiment│    │         │  │\n",
                "│  │Sentiment│───────►│  Sentiment  │─────►│ Features │───►│         │  │\n",
                "│  └─────────┘        └─────────────┘      └──────────┘    │         │  │\n",
                "│                                                           │         │  │\n",
                "│  ┌─────────┐        ┌─────────────┐      ┌──────────┐    │         │  │\n",
                "│  │ GDELT   │        │  Event      │      │ Event    │    │         │  │\n",
                "│  │ Events  │───────►│  Aggregates │─────►│ Features │───►│         │  │\n",
                "│  └─────────┘        └─────────────┘      └──────────┘    │         │  │\n",
                "│                                                           │         │  │\n",
                "│  ┌─────────┐        ┌─────────────┐      ┌──────────┐    │         │  │\n",
                "│  │ FRED    │        │ Interpolated│      │ Macro    │    │         │  │\n",
                "│  │ Macro   │───────►│  Values     │─────►│ Features │───►│         │  │\n",
                "│  └─────────┘        └─────────────┘      └──────────┘    └─────────┘  │\n",
                "│                                                                         │\n",
                "│  Market_Data/       Market_Data/         Market_Data/    Market_Data/  │\n",
                "│     raw/              processed/           features/        final/     │\n",
                "│                                                                         │\n",
                "└─────────────────────────────────────────────────────────────────────────┘\n",
                "```"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "\n",
                "## 10. Expected Outcome\n",
                "\n",
                "### 10.1 Primary Deliverables\n",
                "\n",
                "#### 🎯 Outcome 1: Best Model Identification Per Volatility Regime\n",
                "\n",
                "```\n",
                "┌────────────────────────────────────────────────────────────────┐\n",
                "│              EXPECTED MODEL SELECTION OUTCOME                   │\n",
                "├────────────────────────────────────────────────────────────────┤\n",
                "│                                                                 │\n",
                "│   VOLATILITY           TRAINED MODELS           BEST MODEL    │\n",
                "│   CATEGORY                                                      │\n",
                "│                                                                 │\n",
                "│   ┌──────────┐     ┌────────────────────┐     ┌──────────┐    │\n",
                "│   │ VOLATILE │ ──► │ RF, XGB, LSTM, TF  │ ──► │  Model X │    │\n",
                "│   └──────────┘     └────────────────────┘     └──────────┘    │\n",
                "│                                                                 │\n",
                "│   ┌──────────┐     ┌────────────────────┐     ┌──────────┐    │\n",
                "│   │  STABLE  │ ──► │ RF, XGB, LSTM, TF  │ ──► │  Model Y │    │\n",
                "│   └──────────┘     └────────────────────┘     └──────────┘    │\n",
                "│                                                                 │\n",
                "│   ┌──────────┐     ┌────────────────────┐     ┌──────────┐    │\n",
                "│   │ NON-VOL. │ ──► │ RF, XGB, LSTM, TF  │ ──► │  Model Z │    │\n",
                "│   └──────────┘     └────────────────────┘     └──────────┘    │\n",
                "│                                                                 │\n",
                "└────────────────────────────────────────────────────────────────┘\n",
                "```\n",
                "\n",
                "#### 🎯 Outcome 2: Production-Ready Prediction System\n",
                "\n",
                "| Component | Description |\n",
                "|-----------|-------------|\n",
                "| **ETL Pipeline** | Automated data collection and processing |\n",
                "| **Model Artifacts** | Trained models saved for inference |\n",
                "| **Prediction API** | REST API for real-time predictions |\n",
                "| **MongoDB Storage** | Persistent storage for data and predictions |\n",
                "\n",
                "#### 🎯 Outcome 3: Interactive Dashboard\n",
                "\n",
                "| Feature | Description |\n",
                "|---------|-------------|\n",
                "| **Stock Lookup** | Search and select stocks |\n",
                "| **Prediction Display** | Show next-day trend prediction |\n",
                "| **Volatility Info** | Display stock's volatility category |\n",
                "| **Model Info** | Show which model was used |\n",
                "| **Historical Performance** | Track past prediction accuracy |\n",
                "\n",
                "### 10.2 Research Contributions\n",
                "\n",
                "1. **Comparative Analysis**: Comprehensive comparison of ensemble vs deep learning for Indian stock market\n",
                "\n",
                "2. **Volatility Impact Study**: Understanding how volatility affects model performance\n",
                "\n",
                "3. **Multi-Source Integration**: Framework for combining diverse financial data sources\n",
                "\n",
                "4. **Reproducible Pipeline**: End-to-end ML pipeline that can be adapted for other markets\n",
                "\n",
                "### 10.3 Success Criteria\n",
                "\n",
                "| Metric | Target |\n",
                "|--------|--------|\n",
                "| **Overall Accuracy** | > 55% (better than random) |\n",
                "| **F1 Score** | > 0.55 |\n",
                "| **Model Comparison** | Clear winner per volatility category |\n",
                "| **System Uptime** | Production-ready API |"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "\n",
                "## Summary\n",
                "\n",
                "This notebook establishes the foundational framework for the Financial Market Trend Forecasting project. Key highlights:\n",
                "\n",
                "- **Problem**: Binary classification of next-day stock price direction\n",
                "- **Approach**: Compare ensemble (RF, XGBoost) vs deep learning (LSTM, Transformer) models\n",
                "- **Innovation**: Volatility-based stratification for model selection\n",
                "- **Data**: Multi-source integration (price, technical, global, sentiment, events, macro)\n",
                "- **Output**: Production system with API and dashboard\n",
                "\n",
                "---\n",
                "\n",
                "**Next Notebook:** `02_stock_ingestion.ipynb` — Download and validate stock price data from Yahoo Finance"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.10.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

# Save the notebook
with open(r'c:\Users\Priyanshu\Desktop\Main\Financial-Marketing-Forecasting\ml_pipeline\notebooks\01_problem_statement.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"Notebook created successfully with {len(notebook['cells'])} cells")
